# Generated by Django 4.2.28 on 2026-02-13 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 13, 18, 5, 29, 215907, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
